# -*- coding: utf-8 -*-
"""webスクレイピングテンプレート(配布用) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdQNWWKsdqGHFK58vjFheads-e2WnReM

YoutubeAPI APIキー取得方法(大学アカウントだと取得できないかも）：

 https://kitaka-web.com/youtube-data-api/

# ライブラリ
"""

import os
import requests
import json
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

"""# 動画情報取得のための関数"""

def get_channel_videos(api_key, channel_id, max_results=10):
    """チャンネルIDから動画一覧（動画IDとタイトル）を取得"""
    url = "https://www.googleapis.com/youtube/v3/search"
    params = {
        "part": "snippet",
        "channelId": channel_id,
        "maxResults": max_results,
        "order": "date",  # 新しい順
        "type": "video",
        "key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        videos = []
        for item in data.get("items", []):
            video_id = item["id"]["videoId"]
            title = item["snippet"]["title"]

            published_at = item["snippet"]["publishedAt"]  # ISO 8601 形式の投稿日時
            published_at = datetime.fromisoformat(published_at.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M:%S") # ISO 8601 形式を人間が読みやすい形式に変換

            videos.append({"video_id": video_id, "title": title, "published_at": published_at})
        return videos
    return None

def search_youtube(api_key, query, max_results=5):
    """クエリキーワードから検索結果を取得"""
    url = "https://www.googleapis.com/youtube/v3/search"
    params = {
        "part": "snippet",
        "q": query,
        "maxResults": max_results,
        "type": "video",
        "key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        return None

def get_video_details(api_key, video_id):
    """動画IDからタイトルと視聴回数を取得"""
    url = "https://www.googleapis.com/youtube/v3/videos"
    params = {
        "part": "snippet,statistics",
        "id": video_id,
        "key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        if "items" in data and len(data["items"]) > 0:
            video_info = data["items"][0]
            title = video_info["snippet"]["title"]
            view_count = video_info["statistics"]["viewCount"]
            return {"title": title, "view_count": view_count}
    return None

def get_video_comments(api_key, video_id, max_results=10):
    """動画IDからコメントを取得"""
    url = "https://www.googleapis.com/youtube/v3/commentThreads"
    params = {
        "part": "snippet",
        "videoId": video_id,
        "maxResults": max_results,
        "textFormat": "plainText",
        "key": api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        comments = []
        for item in data.get("items", []):
            comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
            comments.append(comment)
        return comments
    return None

"""# 関数の使用例"""

# parameter
# API key取得方法 https://kitaka-web.com/youtube-data-api/
API_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  # ここにAPIキーを入力

#検索
QUERY = "共通テスト"

# 関数を実行
result = search_youtube(API_KEY, QUERY)

if result:
  for item in result.get("items", []):      # 確認用
        video_id = item["id"].get("videoId")
        title = item["snippet"].get("title")
        print(f"Title: {title}")
        print(f"URL: https://www.youtube.com/watch?v={video_id}")
else:
    print("Failed to fetch data from YouTube API.")

#タイトルと視聴回数
video_id = "sGqp_3qnG8g"  # 動画ID　例：千葉工大fuRo ４脚デモ GMO AIR 設立記者会見

# 関数を実行
video_details = get_video_details(API_KEY, video_id)

# 結果の表示
if video_details:
    print(f"タイトル: {video_details['title']}")
    print(f"視聴回数: {video_details['view_count']}")
else:
    print("動画情報を取得できませんでした")

#動画コメント
video_id = "sGqp_3qnG8g"  # 動画ID　例：千葉工大fuRo ４脚デモ GMO AIR 設立記者会見のコメント

# 関数を実行
comments = get_video_comments(API_KEY, video_id, max_results=10)

# 結果の表示
if comments:
    print("取得したコメント:")
    for idx, comment in enumerate(comments, start=1):
        print(f"{idx}: {comment}")
else:
    print("コメントを取得できませんでした")

# チャンネルの動画一覧．チャンネルIDは「チャンネルのページ」→「このチャンネルの詳細」→「チャンネルを共有」→「チャンネルIDをコピー」
channel_id = "UC_x5XG1OV2P6uZZ5FSM9Ttw"  # 例: Google Developers のチャンネルID

# 関数を実行
videos = get_channel_videos(API_KEY, channel_id, max_results=5)

# 結果の表示
if videos:
    print("取得した動画一覧:")
    for idx, video in enumerate(videos, start=1):
        print(f"{idx}: {video['title']} ({video['published_at']})")
        print(f"    URL: https://www.youtube.com/watch?v={video['video_id']}")
else:
    print("動画を取得できませんでした")

"""# データ分析"""

example_data = [2,2,4,4,6,6,8,8,10,10]

# 折れ線グラフ
plt.figure(figsize=(8, 5))
plt.plot(example_data, marker='o', linestyle='-')
plt.title("Line Chart")
plt.xlabel("Index")
plt.ylabel("Value")
plt.show()

# ヒストグラムの描画
plt.hist(example_data)
plt.show()

# 基本統計量
print("Mean:" + str(np.mean(example_data)))
print("Median:"+ str(np.median(example_data)))
print("Standard Deviation:"+ str(np.std(example_data)))
print("Variance:" + str(np.var(example_data)))
print("Min:" + str(np.min(example_data)))
print("Max:" + str(np.max(example_data)))

# 箱ひげ図サンプルデータ（例：4つのグループのデータ）
data = [
    [3,6,8,1,3,3,3,1],
    [10,5,8,9,0,0,0,5,1],
    [4,8,2,1,3,2],
    [1,6,8,-3,8,4,14,4,4,14,4,4,4],
]

# 箱ひげ図を作成
plt.boxplot(data)

# グラフのタイトルと軸ラベル
plt.title("Box Plot Example")
plt.xlabel("Groups")
plt.ylabel("Values")

# グラフを表示
plt.show()

#!pip install wordcloud janome　　　　　ターミナルでインストールしたから消した
from wordcloud import WordCloud
from janome.tokenizer import Tokenizer

texts = ["私は元気です",
          "今日は大学で大学祭がありました",
          "今日の天気は晴れです",
          "いつも元気でいるためには健康が大切です．",
          "定期テストがあるので，大学に通学しました．"
          ]

# テキストを1つの文字列に結合
text = " ".join(texts)

# Janomeを使って分かち書き
tokenizer = Tokenizer()
words = [token.base_form for token in tokenizer.tokenize(text) if len(token.base_form) > 1]  # 1文字の単語を除外
word_text = " ".join(words)

# Windows用の日本語フォントパス設定
font_path = "C:\\Windows\\Fonts\\msgothic.ttc"  # MS Gothic フォントのパス（ローカルでは通常はこのパスのはず）

# Google Colaboratory用の日本語フォントパス設定
#!apt-get -q -y install fonts-noto-cjk
#font_path = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"

# ワードクラウドの生成
wordcloud = WordCloud(font_path=font_path, background_color="white").generate(word_text)

# ワードクラウドを表示
plt.figure(figsize=(8, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")  # 軸を非表示
plt.show()